version: '3'
services:
  #Node Container
  node:
    build: .
    container_name: angular-node
    tty: true
    user: "node:node"
    working_dir: /usr/src/app
    ports:
      - "4200:4200"
    volumes:
      - ./:/usr/src/app
    command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
